chore(ci): redeploy latest images to main cpin-hp console application

diff --git a/.github/workflows/job-build.yml b/.github/workflows/job-build.yml
--- a/.github/workflows/job-build.yml
+++ b/.github/workflows/job-build.yml
@@ -254,3 +254,28 @@ jobs:
             exit 1
           fi
         continue-on-error: true
+
+  latest:
+    name: Redeploy latest
+    if: ${{ github.ref == format('refs/heads/{0}', 'main') }}
+    runs-on: ubuntu-latest
+    needs:
+      - merge
+    steps:
+      - name: Deploy new image
+        run: |
+          set -e
+
+          RESPONSE_CODE=$(curl -s -w "%{http_code}" -o >(RESPONSE_BODY=$(cat)) -X POST ${{ vars.ARGOCD_URL }}/api/v1/applications/${{ vars.ARGOCD_MAIN_APP_NAME_TEMPLATE }}/sync \
+            -H "Content-Type: application/json" \
+            -H "Authorization: Bearer ${{ secrets.ARGOCD_TOKEN }}" \
+            -d '${{ vars.ARGOCD_MAIN_SYNC_PAYLOAD_TEMPLATE }}')
+
+          echo "HTTP response code: $RESPONSE_CODE"
+
+          if [ "$RESPONSE_CODE" -ne 200 ]; then
+            echo "Error: Non-200 HTTP response detected."
+            echo "Response body: $RESPONSE_BODY"
+            exit 1
+          fi
+        continue-on-error: true
